initStore([
  {
    id: 0,
    title: 'CyberStrike: Neon Uprising (PC/PS5/Xbox)',
    description: 'Dive into a futuristic shooter with dynamic missions and immersive multiplayer battles.',
    price: 69.95,
    discountPrice: 54.95,
    image: 'images/service-1.jpg',
  },
  {
    id: 1,
    title: 'Mystic Quest: Realms Reborn (PC/PS5)',
    description: 'An epic RPG journey through magical worlds with deep storylines and strategic combat.',
    price: 79.95,
    discountPrice: 59.95,
    image: 'images/service-2.jpg',
  },
  {
    id: 2,
    title: 'Galactic Racer X (PC/Switch)',
    description: 'High-speed futuristic racing with customizable ships and challenging tracks.',
    price: 69.95,
    discountPrice: 62.95,
    image: 'images/service-3.jpg',
  },
  {
    id: 3,
    title: 'Soccer Legends 24 (PC/PS5/Xbox)',
    description: 'Next-gen football simulation with realistic player AI and global tournaments.',
    price: 59.95,
    discountPrice: 49.95,
    image: 'images/service-4.jpg',
  },
  {
    id: 4,
    title: 'Shadow Mansion: Dark Secrets (PC/PS5/Xbox)',
    description: 'Chilling horror adventure with mysterious puzzles and atmospheric storytelling.',
    price: 39.95,
    discountPrice: 29.95,
    image: 'images/service-5.jpg',
  },
  {
    id: 5,
    title: 'Battle Arena Ultimate (Switch)',
    description: 'Fast-paced fighting game with a wide roster of fighters and explosive combos.',
    price: 59.95,
    discountPrice: 49.95,
    image: 'images/service-6.jpg',
  },
]);
